"""add_deeplink_to_notifications

Revision ID: 0f2150774064
Revises: 8cfc938ba7fd
Create Date: 2026-03-09 16:19:41.703297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f2150774064'
down_revision: Union[str, None] = '8cfc938ba7fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('deeplink', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'deeplink')
    # ### end Alembic commands ###
