"""add_qr_points_scan_log

Revision ID: 2594f1f64d16
Revises: 5f3820d1005c
Create Date: 2026-02-06 16:55:46.195485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2594f1f64d16'
down_revision: Union[str, None] = '5f3820d1005c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scanner_id', sa.Integer(), nullable=False),
    sa.Column('scanned_id', sa.Integer(), nullable=False),
    sa.Column('points_awarded', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scanned_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scanner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scanner_id', 'scanned_id', name='uq_scan_pair')
    )
    op.create_index(op.f('ix_scan_logs_scanned_id'), 'scan_logs', ['scanned_id'], unique=False)
    op.create_index(op.f('ix_scan_logs_scanner_id'), 'scan_logs', ['scanner_id'], unique=False)
    op.add_column('users', sa.Column('points', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'points')
    op.drop_index(op.f('ix_scan_logs_scanner_id'), table_name='scan_logs')
    op.drop_index(op.f('ix_scan_logs_scanned_id'), table_name='scan_logs')
    op.drop_table('scan_logs')
    # ### end Alembic commands ###
