"""add meeting model

Revision ID: 5c6e96c9db02
Revises: 39d18624946b
Create Date: 2026-01-29 22:40:58.318815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c6e96c9db02'
down_revision: Union[str, None] = '39d18624946b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('proposed_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('proposed_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'declined', 'cancelled', 'expired', name='meeting_status'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('map_feature_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['map_feature_id'], ['map_features.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetings_expires_at'), 'meetings', ['expires_at'], unique=False)
    op.create_index(op.f('ix_meetings_map_feature_id'), 'meetings', ['map_feature_id'], unique=False)
    op.create_index(op.f('ix_meetings_proposed_start'), 'meetings', ['proposed_start'], unique=False)
    op.create_index(op.f('ix_meetings_recipient_id'), 'meetings', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_meetings_requester_id'), 'meetings', ['requester_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meetings_requester_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_recipient_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_proposed_start'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_map_feature_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_expires_at'), table_name='meetings')
    op.drop_table('meetings')
    # Drop the enum type
    op.execute("DROP TYPE IF EXISTS meeting_status")
    # ### end Alembic commands ###
