"""add polls tables

Revision ID: 5f3820d1005c
Revises: 0272725ac4be
Create Date: 2026-02-01 12:02:12.751123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f3820d1005c'
down_revision: Union[str, None] = '0272725ac4be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('polls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_polls_created_by'), 'polls', ['created_by'], unique=False)
    op.create_index(op.f('ix_polls_session_id'), 'polls', ['session_id'], unique=False)
    op.create_table('poll_options',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_options_poll_id'), 'poll_options', ['poll_id'], unique=False)
    op.create_table('poll_answers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['poll_options.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('poll_id', 'user_id', name='uq_poll_user_vote')
    )
    op.create_index(op.f('ix_poll_answers_option_id'), 'poll_answers', ['option_id'], unique=False)
    op.create_index(op.f('ix_poll_answers_poll_id'), 'poll_answers', ['poll_id'], unique=False)
    op.create_index(op.f('ix_poll_answers_user_id'), 'poll_answers', ['user_id'], unique=False)
    op.drop_index('ix_speakers_user_id', table_name='speakers')
    op.drop_table('speakers')
    op.drop_index('ix_exhibitors_user_id', table_name='exhibitors')
    op.drop_table('exhibitors')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exhibitors',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('booth_code', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='exhibitors_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='exhibitors_pkey'),
    sa.UniqueConstraint('user_id', name='exhibitors_user_id_key')
    )
    op.create_index('ix_exhibitors_user_id', 'exhibitors', ['user_id'], unique=False)
    op.create_table('speakers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='speakers_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='speakers_pkey')
    )
    op.create_index('ix_speakers_user_id', 'speakers', ['user_id'], unique=True)
    op.drop_index(op.f('ix_poll_answers_user_id'), table_name='poll_answers')
    op.drop_index(op.f('ix_poll_answers_poll_id'), table_name='poll_answers')
    op.drop_index(op.f('ix_poll_answers_option_id'), table_name='poll_answers')
    op.drop_table('poll_answers')
    op.drop_index(op.f('ix_poll_options_poll_id'), table_name='poll_options')
    op.drop_table('poll_options')
    op.drop_index(op.f('ix_polls_session_id'), table_name='polls')
    op.drop_index(op.f('ix_polls_created_by'), table_name='polls')
    op.drop_table('polls')
    # ### end Alembic commands ###
