"""add created_by to sessions

Revision ID: 644b1ae24542
Revises: de55b222e447
Create Date: 2026-02-10 13:10:20.238490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '644b1ae24542'
down_revision: Union[str, None] = 'de55b222e447'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_sessions_created_by'), 'sessions', ['created_by'], unique=False)
    op.create_foreign_key(None, 'sessions', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_index(op.f('ix_sessions_created_by'), table_name='sessions')
    op.drop_column('sessions', 'created_by')
    # ### end Alembic commands ###
