"""add exhibitor product showcases

Revision ID: 66d2be694423
Revises: a99b15ac1166
Create Date: 2026-03-09 14:09:41.673536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66d2be694423'
down_revision: Union[str, None] = 'a99b15ac1166'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exhibitor_showcases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exhibitor_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('icon_url', sa.String(length=512), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['exhibitor_id'], ['exhibitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exhibitor_showcases_exhibitor_id'), 'exhibitor_showcases', ['exhibitor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exhibitor_showcases_exhibitor_id'), table_name='exhibitor_showcases')
    op.drop_table('exhibitor_showcases')
    # ### end Alembic commands ###
