"""add_outdoor_map_fields_to_venues

Revision ID: 864b664bfe45
Revises: a5af2644b839
Create Date: 2026-03-05 10:53:36.982653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '864b664bfe45'
down_revision: Union[str, None] = 'a5af2644b839'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('category', sa.String(length=20), server_default='exhibitor', nullable=False))
    op.add_column('venues', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('venues', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('venues', sa.Column('company', sa.String(length=200), nullable=True))
    op.add_column('venues', sa.Column('booth_number', sa.String(length=20), nullable=True))
    op.add_column('venues', sa.Column('extrusion_height', sa.Integer(), server_default='15', nullable=False))
    op.add_column('venues', sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False))
    op.add_column('venues', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('venues', sa.Column('geojson_geometry', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'geojson_geometry')
    op.drop_column('venues', 'is_active')
    op.drop_column('venues', 'sort_order')
    op.drop_column('venues', 'extrusion_height')
    op.drop_column('venues', 'booth_number')
    op.drop_column('venues', 'company')
    op.drop_column('venues', 'avatar_url')
    op.drop_column('venues', 'description')
    op.drop_column('venues', 'category')
    # ### end Alembic commands ###
