"""add poll_id back to sessions

Revision ID: a5af2644b839
Revises: 9c4ed44b0e46
Create Date: 2026-02-10 21:24:47.706735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5af2644b839'
down_revision: Union[str, None] = '9c4ed44b0e46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('poll_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'poll_id')
    # ### end Alembic commands ###
