"""add cover_url to users

Revision ID: a99b15ac1166
Revises: f9ec14d9785d
Create Date: 2026-03-09 13:02:52.122993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a99b15ac1166'
down_revision: Union[str, None] = 'f9ec14d9785d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cover_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cover_url')
    # ### end Alembic commands ###
