"""add exhibitor_whitelist table

Revision ID: abec3d91d131
Revises: f5a320ef1b3c
Create Date: 2026-02-09 18:30:25.370908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abec3d91d131'
down_revision: Union[str, None] = 'f5a320ef1b3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exhibitor_whitelist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exhibitor_whitelist_email'), 'exhibitor_whitelist', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exhibitor_whitelist_email'), table_name='exhibitor_whitelist')
    op.drop_table('exhibitor_whitelist')
    # ### end Alembic commands ###
