"""exhibitor chat use user_id instead of exhibitor_id

Revision ID: c8c773a92987
Revises: e4ef6f703399
Create Date: 2026-02-16 15:52:36.432438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8c773a92987'
down_revision: Union[str, None] = 'e4ef6f703399'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exhibitor_chat_messages', sa.Column('exhibitor_user_id', sa.Integer(), nullable=False))
    op.drop_index('ix_exhibitor_chat_messages_exhibitor_id', table_name='exhibitor_chat_messages')
    op.create_index(op.f('ix_exhibitor_chat_messages_exhibitor_user_id'), 'exhibitor_chat_messages', ['exhibitor_user_id'], unique=False)
    op.drop_constraint('exhibitor_chat_messages_exhibitor_id_fkey', 'exhibitor_chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'exhibitor_chat_messages', 'users', ['exhibitor_user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('exhibitor_chat_messages', 'exhibitor_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exhibitor_chat_messages', sa.Column('exhibitor_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'exhibitor_chat_messages', type_='foreignkey')
    op.create_foreign_key('exhibitor_chat_messages_exhibitor_id_fkey', 'exhibitor_chat_messages', 'exhibitors', ['exhibitor_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_exhibitor_chat_messages_exhibitor_user_id'), table_name='exhibitor_chat_messages')
    op.create_index('ix_exhibitor_chat_messages_exhibitor_id', 'exhibitor_chat_messages', ['exhibitor_id'], unique=False)
    op.drop_column('exhibitor_chat_messages', 'exhibitor_user_id')
    # ### end Alembic commands ###
