"""add onboarding tables

Revision ID: ce5c5e59b8ce
Revises: 5c6e96c9db02
Create Date: 2026-01-31 09:20:45.701227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'ce5c5e59b8ce'
down_revision: Union[str, None] = '5c6e96c9db02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_name'), 'goals', ['name'], unique=True)
    op.create_table('user_goals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'goal_id', name='uq_user_goal')
    )
    op.create_index(op.f('ix_user_goals_goal_id'), 'user_goals', ['goal_id'], unique=False)
    op.create_index(op.f('ix_user_goals_user_id'), 'user_goals', ['user_id'], unique=False)
    op.create_table('user_onboarding',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('experience_level', sa.Enum('beginner', 'early_stage', 'experienced', 'expert', name='experience_level_enum'), nullable=True),
    sa.Column('discussion_topics', postgresql.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('status', sa.Enum('pending', 'completed', 'skipped', name='onboarding_status_enum'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_onboarding_user_id'), 'user_onboarding', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_onboarding_user_id'), table_name='user_onboarding')
    op.drop_table('user_onboarding')
    op.drop_index(op.f('ix_user_goals_user_id'), table_name='user_goals')
    op.drop_index(op.f('ix_user_goals_goal_id'), table_name='user_goals')
    op.drop_table('user_goals')
    op.drop_index(op.f('ix_goals_name'), table_name='goals')
    op.drop_table('goals')
    # Drop enum types
    sa.Enum(name='experience_level_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='onboarding_status_enum').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
