"""add_session_qa_tables

Revision ID: dff922812e5c
Revises: g3c4a1b2d5e6
Create Date: 2026-03-11 21:44:35.795005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dff922812e5c'
down_revision: Union[str, None] = 'g3c4a1b2d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('answered_by', sa.Integer(), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['answered_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_questions_answered_by'), 'session_questions', ['answered_by'], unique=False)
    op.create_index(op.f('ix_session_questions_session_id'), 'session_questions', ['session_id'], unique=False)
    op.create_index(op.f('ix_session_questions_user_id'), 'session_questions', ['user_id'], unique=False)
    op.create_table('session_question_likes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['session_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'user_id', name='uq_question_user_like')
    )
    op.create_index(op.f('ix_session_question_likes_question_id'), 'session_question_likes', ['question_id'], unique=False)
    op.create_index(op.f('ix_session_question_likes_user_id'), 'session_question_likes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_question_likes_user_id'), table_name='session_question_likes')
    op.drop_index(op.f('ix_session_question_likes_question_id'), table_name='session_question_likes')
    op.drop_table('session_question_likes')
    op.drop_index(op.f('ix_session_questions_user_id'), table_name='session_questions')
    op.drop_index(op.f('ix_session_questions_session_id'), table_name='session_questions')
    op.drop_index(op.f('ix_session_questions_answered_by'), table_name='session_questions')
    op.drop_table('session_questions')
    # ### end Alembic commands ###
