"""add session and exhibitor chat messages

Revision ID: e4ef6f703399
Revises: a5af2644b839
Create Date: 2026-02-16 14:51:49.146868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4ef6f703399'
down_revision: Union[str, None] = 'a5af2644b839'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exhibitors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('booth_code', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exhibitors_user_id'), 'exhibitors', ['user_id'], unique=True)
    op.create_table('exhibitor_chat_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exhibitor_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exhibitor_id'], ['exhibitors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exhibitor_chat_messages_exhibitor_id'), 'exhibitor_chat_messages', ['exhibitor_id'], unique=False)
    op.create_index(op.f('ix_exhibitor_chat_messages_sender_id'), 'exhibitor_chat_messages', ['sender_id'], unique=False)
    op.create_table('session_chat_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_chat_messages_sender_id'), 'session_chat_messages', ['sender_id'], unique=False)
    op.create_index(op.f('ix_session_chat_messages_session_id'), 'session_chat_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_chat_messages_session_id'), table_name='session_chat_messages')
    op.drop_index(op.f('ix_session_chat_messages_sender_id'), table_name='session_chat_messages')
    op.drop_table('session_chat_messages')
    op.drop_index(op.f('ix_exhibitor_chat_messages_sender_id'), table_name='exhibitor_chat_messages')
    op.drop_index(op.f('ix_exhibitor_chat_messages_exhibitor_id'), table_name='exhibitor_chat_messages')
    op.drop_table('exhibitor_chat_messages')
    op.drop_index(op.f('ix_exhibitors_user_id'), table_name='exhibitors')
    op.drop_table('exhibitors')
    # ### end Alembic commands ###
