"""add_group_and_session_interests

Revision ID: f5a320ef1b3c
Revises: 0f27203c2b2d
Create Date: 2026-02-09 11:19:48.629258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5a320ef1b3c'
down_revision: Union[str, None] = '0f27203c2b2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_interests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('interest_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interest_id'], ['interests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'interest_id', name='uq_group_interest')
    )
    op.create_index(op.f('ix_group_interests_group_id'), 'group_interests', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_interests_interest_id'), 'group_interests', ['interest_id'], unique=False)
    op.create_table('session_interests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('interest_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['interest_id'], ['interests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'interest_id', name='uq_session_interest')
    )
    op.create_index(op.f('ix_session_interests_interest_id'), 'session_interests', ['interest_id'], unique=False)
    op.create_index(op.f('ix_session_interests_session_id'), 'session_interests', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_interests_session_id'), table_name='session_interests')
    op.drop_index(op.f('ix_session_interests_interest_id'), table_name='session_interests')
    op.drop_table('session_interests')
    op.drop_index(op.f('ix_group_interests_interest_id'), table_name='group_interests')
    op.drop_index(op.f('ix_group_interests_group_id'), table_name='group_interests')
    op.drop_table('group_interests')
    # ### end Alembic commands ###
