"""add exhibitor_staff table

Revision ID: f9ec14d9785d
Revises: 6f3246840607
Create Date: 2026-03-09 11:53:14.797587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9ec14d9785d'
down_revision: Union[str, None] = '6f3246840607'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exhibitor_staff',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exhibitor_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=128), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['exhibitor_id'], ['exhibitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exhibitor_staff_exhibitor_id'), 'exhibitor_staff', ['exhibitor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exhibitor_staff_exhibitor_id'), table_name='exhibitor_staff')
    op.drop_table('exhibitor_staff')
    # ### end Alembic commands ###
